# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :'mysql-master' => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.10'
  },
  :'mysql-slave' => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.11'
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
        vb.name = boxname.to_s
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        # Подключаем дополнительные диски
#        vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 5 * 1024]
#        vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]
      end
      
      box.vm.provision :shell do |s|
        s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
      end
    end
    
    config.vm.provision "mysql_replication", type:'ansible' do |ansible|
      ansible.inventory_path = 'inventory'
      ansible.playbook = 'mysql.yml'
    end
  end
end
