---

mysql:
# 01-base.cnf
  pid_file: /var/run/mysqld/mysqld.pid
  log_error: /var/log/mysqld.log
  datadir: /var/lib/mysql
  socket: /var/lib/mysql/mysql.sock
  symbolic_links: "0"

  server_id: "2"
  innodb_file_per_table: "1"
  skip_name_resolve: true

# 02-max-connections.cnf
  wait_timeout: "60"
  max_connections: "500"

# 03-performance.cnf
  skip_external_locking: true
  key_buffer_size: "384M"
  max_allowed_packet: "16M"
  table_open_cache: "5000"
  sort_buffer_size: "64M"
  join_buffer_size: "64M"
  read_buffer_size: "2M"
  read_rnd_buffer_size: "8M"
  myisam_sort_buffer_size: "64M"
  thread_cache_size: "8"
  query_cache_limit: "64M"
  query_cache_size: "1024M"
  tmp_table_size: "1024M"
  max_heap_table_size: "1024M"

# 04-slow-query.cnf
  slow_query_log: "1"
  log_output: "TABLE"
  long_query_time: "2"

# 05-binlog.cnf
  log_bin: "mysql-bin"
  expire_logs_days: "7"
  max_binlog_size: "16M"
  binlog_format: "MIXED"

  log_slave_updates: "On"
  gtid_mode: "On"
  enforce_gtid_consistency: "On"

  replicate_ignore_table: true
